apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
      - image: web:v1
        name: web
        env:
          - name: WEATHER_SERVICE
            value: http://service-weather
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
  labels:
    app: web
    service: web
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-v1
  labels:
    app: weather
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      version: v1
  template:
    metadata:
      labels:
        app: weather
        version: v1
    spec:
      containers:
      - image: weather-service:v1
        name: weather
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-v2
  labels:
    app: weather
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      version: v2
  template:
    metadata:
      labels:
        app: weather
        version: v2
    spec:
      containers:
      - image: weather-service:v2
        name: weather
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-v3
  labels:
    app: weather
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      version: v3
  template:
    metadata:
      labels:
        app: weather
        version: v3
    spec:
      containers:
      - image: weather-service:v3
        name: weather
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-weather
  labels:
    app: weather
    service: weather
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: weather